# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1340, 808)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ESDL_lab_softwareicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stopBTN = QtWidgets.QPushButton(self.centralwidget)
        self.stopBTN.setGeometry(QtCore.QRect(1110, 20, 211, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopBTN.setFont(font)
        self.stopBTN.setObjectName("stopBTN")
        self.realtimelabel = QtWidgets.QLabel(self.centralwidget)
        self.realtimelabel.setGeometry(QtCore.QRect(20, 80, 640, 480))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.realtimelabel.setFont(font)
        self.realtimelabel.setFrameShape(QtWidgets.QFrame.Box)
        self.realtimelabel.setText("")
        self.realtimelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.realtimelabel.setObjectName("realtimelabel")
        self.datetimetilte = QtWidgets.QLabel(self.centralwidget)
        self.datetimetilte.setGeometry(QtCore.QRect(20, 580, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.datetimetilte.setFont(font)
        self.datetimetilte.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.datetimetilte.setAlignment(QtCore.Qt.AlignCenter)
        self.datetimetilte.setObjectName("datetimetilte")
        self.datetime = QtWidgets.QLabel(self.centralwidget)
        self.datetime.setGeometry(QtCore.QRect(130, 580, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.datetime.setFont(font)
        self.datetime.setAutoFillBackground(False)
        self.datetime.setStyleSheet("color: rgb(0, 170, 0);")
        self.datetime.setFrameShape(QtWidgets.QFrame.Panel)
        self.datetime.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.datetime.setMidLineWidth(0)
        self.datetime.setText("")
        self.datetime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.datetime.setObjectName("datetime")
        self.systemtitle = QtWidgets.QLabel(self.centralwidget)
        self.systemtitle.setGeometry(QtCore.QRect(20, 20, 421, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.systemtitle.setFont(font)
        self.systemtitle.setStyleSheet("color: rgb(255, 143, 14);")
        self.systemtitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.systemtitle.setObjectName("systemtitle")
        self.maskdetectorlabel = QtWidgets.QLabel(self.centralwidget)
        self.maskdetectorlabel.setGeometry(QtCore.QRect(680, 80, 640, 480))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.maskdetectorlabel.setFont(font)
        self.maskdetectorlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.maskdetectorlabel.setText("")
        self.maskdetectorlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.maskdetectorlabel.setObjectName("maskdetectorlabel")
        self.Distancetitle = QtWidgets.QLabel(self.centralwidget)
        self.Distancetitle.setGeometry(QtCore.QRect(960, 640, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Distancetitle.setFont(font)
        self.Distancetitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.Distancetitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Distancetitle.setObjectName("Distancetitle")
        self.distance = QtWidgets.QLabel(self.centralwidget)
        self.distance.setGeometry(QtCore.QRect(1070, 640, 191, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.distance.setFont(font)
        self.distance.setAutoFillBackground(False)
        self.distance.setStyleSheet("color: rgb(0, 170, 0);")
        self.distance.setFrameShape(QtWidgets.QFrame.Panel)
        self.distance.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.distance.setMidLineWidth(0)
        self.distance.setText("")
        self.distance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.distance.setObjectName("distance")
        self.ID = QtWidgets.QLineEdit(self.centralwidget)
        self.ID.setGeometry(QtCore.QRect(570, 580, 211, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ID.setFont(font)
        self.ID.setAutoFillBackground(False)
        self.ID.setStyleSheet("color: rgb(0, 170, 0);")
        self.ID.setText("")
        self.ID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ID.setObjectName("ID")
        self.CardIDtitle = QtWidgets.QLabel(self.centralwidget)
        self.CardIDtitle.setGeometry(QtCore.QRect(470, 580, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CardIDtitle.setFont(font)
        self.CardIDtitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.CardIDtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.CardIDtitle.setObjectName("CardIDtitle")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(420, 640, 191, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setAutoFillBackground(False)
        self.name.setStyleSheet("color: rgb(0, 170, 0);")
        self.name.setFrameShape(QtWidgets.QFrame.Panel)
        self.name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.name.setMidLineWidth(0)
        self.name.setText("")
        self.name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name.setObjectName("name")
        self.Nametitle = QtWidgets.QLabel(self.centralwidget)
        self.Nametitle.setGeometry(QtCore.QRect(330, 640, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Nametitle.setFont(font)
        self.Nametitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.Nametitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Nametitle.setObjectName("Nametitle")
        self.temperature = QtWidgets.QLabel(self.centralwidget)
        self.temperature.setGeometry(QtCore.QRect(710, 640, 191, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temperature.setFont(font)
        self.temperature.setAutoFillBackground(False)
        self.temperature.setStyleSheet("color: rgb(0, 170, 0);")
        self.temperature.setFrameShape(QtWidgets.QFrame.Panel)
        self.temperature.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.temperature.setMidLineWidth(0)
        self.temperature.setText("")
        self.temperature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temperature.setObjectName("temperature")
        self.Temptitle = QtWidgets.QLabel(self.centralwidget)
        self.Temptitle.setGeometry(QtCore.QRect(620, 640, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Temptitle.setFont(font)
        self.Temptitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.Temptitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Temptitle.setObjectName("Temptitle")
        self.startBTN = QtWidgets.QPushButton(self.centralwidget)
        self.startBTN.setGeometry(QtCore.QRect(890, 20, 211, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.startBTN.setFont(font)
        self.startBTN.setObjectName("startBTN")
        self.StuIDtitle = QtWidgets.QLabel(self.centralwidget)
        self.StuIDtitle.setGeometry(QtCore.QRect(40, 640, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StuIDtitle.setFont(font)
        self.StuIDtitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.StuIDtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.StuIDtitle.setObjectName("StuIDtitle")
        self.StuID = QtWidgets.QLabel(self.centralwidget)
        self.StuID.setGeometry(QtCore.QRect(130, 640, 191, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StuID.setFont(font)
        self.StuID.setAutoFillBackground(False)
        self.StuID.setStyleSheet("color: rgb(0, 170, 0);")
        self.StuID.setFrameShape(QtWidgets.QFrame.Panel)
        self.StuID.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.StuID.setMidLineWidth(0)
        self.StuID.setText("")
        self.StuID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StuID.setObjectName("StuID")
        self.Tempdegreetitle = QtWidgets.QLabel(self.centralwidget)
        self.Tempdegreetitle.setGeometry(QtCore.QRect(900, 640, 41, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Tempdegreetitle.setFont(font)
        self.Tempdegreetitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.Tempdegreetitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Tempdegreetitle.setObjectName("Tempdegreetitle")
        self.distunittitle = QtWidgets.QLabel(self.centralwidget)
        self.distunittitle.setGeometry(QtCore.QRect(1260, 640, 41, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.distunittitle.setFont(font)
        self.distunittitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.distunittitle.setAlignment(QtCore.Qt.AlignCenter)
        self.distunittitle.setObjectName("distunittitle")
        self.Info = QtWidgets.QLabel(self.centralwidget)
        self.Info.setGeometry(QtCore.QRect(290, 707, 771, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.Info.setFont(font)
        self.Info.setAutoFillBackground(False)
        self.Info.setStyleSheet("color: rgb(0,0,254)")
        self.Info.setFrameShape(QtWidgets.QFrame.Panel)
        self.Info.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Info.setMidLineWidth(0)
        self.Info.setText("")
        self.Info.setAlignment(QtCore.Qt.AlignCenter)
        self.Info.setWordWrap(False)
        self.Info.setObjectName("Info")
        self.cleancardidBTN = QtWidgets.QPushButton(self.centralwidget)
        self.cleancardidBTN.setGeometry(QtCore.QRect(800, 580, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cleancardidBTN.setFont(font)
        self.cleancardidBTN.setObjectName("cleancardidBTN")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IHMIoTSystam"))
        self.stopBTN.setText(_translate("MainWindow", "System Stop"))
        self.datetimetilte.setText(_translate("MainWindow", "Datetime"))
        self.systemtitle.setText(_translate("MainWindow", "智慧健康管理物聯網"))
        self.Distancetitle.setText(_translate("MainWindow", "Distance"))
        self.CardIDtitle.setText(_translate("MainWindow", "Card ID"))
        self.Nametitle.setText(_translate("MainWindow", "Name"))
        self.Temptitle.setText(_translate("MainWindow", "Temp."))
        self.startBTN.setText(_translate("MainWindow", "System Start"))
        self.StuIDtitle.setText(_translate("MainWindow", "StuID"))
        self.Tempdegreetitle.setText(_translate("MainWindow", "°C"))
        self.distunittitle.setText(_translate("MainWindow", "CM"))
        self.cleancardidBTN.setText(_translate("MainWindow", "Clean Card ID"))
