# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI002.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem
from PyQt5.QtWidgets import QHeaderView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1369, 887)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ESDL_lab_softwareicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.systemtitle = QtWidgets.QLabel(self.centralwidget)
        self.systemtitle.setGeometry(QtCore.QRect(20, 17, 421, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.systemtitle.setFont(font)
        self.systemtitle.setStyleSheet("color: rgb(255, 143, 14);")
        self.systemtitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.systemtitle.setObjectName("systemtitle")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 1341, 801))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.mainpage = QtWidgets.QWidget()
        self.mainpage.setObjectName("mainpage")
        self.StuIDtitle = QtWidgets.QLabel(self.mainpage)
        self.StuIDtitle.setGeometry(QtCore.QRect(37, 579, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StuIDtitle.setFont(font)
        self.StuIDtitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.StuIDtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.StuIDtitle.setObjectName("StuIDtitle")
        self.Info = QtWidgets.QLabel(self.mainpage)
        self.Info.setGeometry(QtCore.QRect(287, 646, 771, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.Info.setFont(font)
        self.Info.setAutoFillBackground(False)
        self.Info.setStyleSheet("color: rgb(0, 0, 127);")
        self.Info.setFrameShape(QtWidgets.QFrame.Panel)
        self.Info.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Info.setMidLineWidth(0)
        self.Info.setText("")
        self.Info.setAlignment(QtCore.Qt.AlignCenter)
        self.Info.setWordWrap(False)
        self.Info.setObjectName("Info")
        self.maskdetectorlabel = QtWidgets.QLabel(self.mainpage)
        self.maskdetectorlabel.setGeometry(QtCore.QRect(677, 19, 640, 480))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.maskdetectorlabel.setFont(font)
        self.maskdetectorlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.maskdetectorlabel.setText("")
        self.maskdetectorlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.maskdetectorlabel.setObjectName("maskdetectorlabel")
        self.cleancardidBTN = QtWidgets.QPushButton(self.mainpage)
        self.cleancardidBTN.setGeometry(QtCore.QRect(797, 519, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cleancardidBTN.setFont(font)
        self.cleancardidBTN.setObjectName("cleancardidBTN")
        self.CardIDtitle = QtWidgets.QLabel(self.mainpage)
        self.CardIDtitle.setGeometry(QtCore.QRect(467, 519, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CardIDtitle.setFont(font)
        self.CardIDtitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.CardIDtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.CardIDtitle.setObjectName("CardIDtitle")
        self.datetimetilte = QtWidgets.QLabel(self.mainpage)
        self.datetimetilte.setGeometry(QtCore.QRect(17, 519, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.datetimetilte.setFont(font)
        self.datetimetilte.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.datetimetilte.setAlignment(QtCore.Qt.AlignCenter)
        self.datetimetilte.setObjectName("datetimetilte")
        self.name = QtWidgets.QLabel(self.mainpage)
        self.name.setGeometry(QtCore.QRect(417, 579, 191, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setAutoFillBackground(False)
        self.name.setStyleSheet("color: rgb(0, 170, 0);")
        self.name.setFrameShape(QtWidgets.QFrame.Panel)
        self.name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.name.setMidLineWidth(0)
        self.name.setText("")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.distunittitle = QtWidgets.QLabel(self.mainpage)
        self.distunittitle.setGeometry(QtCore.QRect(1257, 579, 41, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.distunittitle.setFont(font)
        self.distunittitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.distunittitle.setAlignment(QtCore.Qt.AlignCenter)
        self.distunittitle.setObjectName("distunittitle")
        self.datetime = QtWidgets.QLabel(self.mainpage)
        self.datetime.setGeometry(QtCore.QRect(127, 519, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.datetime.setFont(font)
        self.datetime.setAutoFillBackground(False)
        self.datetime.setStyleSheet("color: rgb(0, 170, 0);")
        self.datetime.setFrameShape(QtWidgets.QFrame.Panel)
        self.datetime.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.datetime.setMidLineWidth(0)
        self.datetime.setText("")
        self.datetime.setAlignment(QtCore.Qt.AlignCenter)
        self.datetime.setObjectName("datetime")
        self.distance = QtWidgets.QLabel(self.mainpage)
        self.distance.setGeometry(QtCore.QRect(1067, 579, 191, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.distance.setFont(font)
        self.distance.setAutoFillBackground(False)
        self.distance.setStyleSheet("color: rgb(0, 170, 0);")
        self.distance.setFrameShape(QtWidgets.QFrame.Panel)
        self.distance.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.distance.setMidLineWidth(0)
        self.distance.setText("")
        self.distance.setAlignment(QtCore.Qt.AlignCenter)
        self.distance.setObjectName("distance")
        self.Distancetitle = QtWidgets.QLabel(self.mainpage)
        self.Distancetitle.setGeometry(QtCore.QRect(957, 579, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Distancetitle.setFont(font)
        self.Distancetitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.Distancetitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Distancetitle.setObjectName("Distancetitle")
        self.Temptitle = QtWidgets.QLabel(self.mainpage)
        self.Temptitle.setGeometry(QtCore.QRect(617, 579, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Temptitle.setFont(font)
        self.Temptitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.Temptitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Temptitle.setObjectName("Temptitle")
        self.realtimelabel = QtWidgets.QLabel(self.mainpage)
        self.realtimelabel.setGeometry(QtCore.QRect(17, 19, 640, 480))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.realtimelabel.setFont(font)
        self.realtimelabel.setFrameShape(QtWidgets.QFrame.Box)
        self.realtimelabel.setText("")
        self.realtimelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.realtimelabel.setObjectName("realtimelabel")
        self.Nametitle = QtWidgets.QLabel(self.mainpage)
        self.Nametitle.setGeometry(QtCore.QRect(327, 579, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Nametitle.setFont(font)
        self.Nametitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.Nametitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Nametitle.setObjectName("Nametitle")
        self.StuID = QtWidgets.QLabel(self.mainpage)
        self.StuID.setGeometry(QtCore.QRect(127, 579, 191, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StuID.setFont(font)
        self.StuID.setAutoFillBackground(False)
        self.StuID.setStyleSheet("color: rgb(0, 170, 0);")
        self.StuID.setFrameShape(QtWidgets.QFrame.Panel)
        self.StuID.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.StuID.setMidLineWidth(0)
        self.StuID.setText("")
        self.StuID.setAlignment(QtCore.Qt.AlignCenter)
        self.StuID.setObjectName("StuID")
        self.Tempdegreetitle = QtWidgets.QLabel(self.mainpage)
        self.Tempdegreetitle.setGeometry(QtCore.QRect(897, 579, 41, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Tempdegreetitle.setFont(font)
        self.Tempdegreetitle.setStyleSheet("\n"
"color: rgb(0,0,0);")
        self.Tempdegreetitle.setAlignment(QtCore.Qt.AlignCenter)
        self.Tempdegreetitle.setObjectName("Tempdegreetitle")
        self.temperature = QtWidgets.QLabel(self.mainpage)
        self.temperature.setGeometry(QtCore.QRect(707, 579, 191, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temperature.setFont(font)
        self.temperature.setAutoFillBackground(False)
        self.temperature.setStyleSheet("color: rgb(0, 170, 0);")
        self.temperature.setFrameShape(QtWidgets.QFrame.Panel)
        self.temperature.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.temperature.setMidLineWidth(0)
        self.temperature.setText("")
        self.temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature.setObjectName("temperature")
        self.ID = QtWidgets.QLineEdit(self.mainpage)
        self.ID.setGeometry(QtCore.QRect(567, 520, 211, 41))
        self.ID.setStyleSheet("color: rgb(0, 170, 0);")
        self.ID.setAlignment(QtCore.Qt.AlignCenter)
        self.ID.setObjectName("ID")
        self.tabWidget.addTab(self.mainpage, "")
        self.logpage = QtWidgets.QWidget()
        self.logpage.setObjectName("logpage")
        self.model=QStandardItemModel(0,0)
        self.model.setHorizontalHeaderLabels(['時間','人員編號','姓名','額溫','口罩配戴'])
        self.logview = QtWidgets.QTableView(self.logpage)
        self.logview.setGeometry(QtCore.QRect(10, 10, 1311, 721))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.logview.setFont(font)
        self.logview.setObjectName("logview")
        #self.logview.setTextAlignment(QtCore.Qt.AlignCenter)
        self.logview.setModel(self.model)
        self.logview.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tabWidget.addTab(self.logpage, "")
        self.stopBTN = QtWidgets.QPushButton(self.centralwidget)
        self.stopBTN.setGeometry(QtCore.QRect(1130, 60, 211, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopBTN.setFont(font)
        self.stopBTN.setObjectName("stopBTN")
        self.startBTN = QtWidgets.QPushButton(self.centralwidget)
        self.startBTN.setGeometry(QtCore.QRect(910, 60, 211, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.startBTN.setFont(font)
        self.startBTN.setObjectName("startBTN")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IHMIoTSystam"))
        self.systemtitle.setText(_translate("MainWindow", "智慧健康管理物聯網"))
        self.StuIDtitle.setText(_translate("MainWindow", "StuID"))
        self.cleancardidBTN.setText(_translate("MainWindow", "Clean Card ID"))
        self.CardIDtitle.setText(_translate("MainWindow", "Card ID"))
        self.datetimetilte.setText(_translate("MainWindow", "Datetime"))
        self.distunittitle.setText(_translate("MainWindow", "CM"))
        self.Distancetitle.setText(_translate("MainWindow", "Distance"))
        self.Temptitle.setText(_translate("MainWindow", "Temp."))
        self.Nametitle.setText(_translate("MainWindow", "Name"))
        self.Tempdegreetitle.setText(_translate("MainWindow", "°C"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainpage), _translate("MainWindow", "系統主頁"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logpage), _translate("MainWindow", "辨識紀錄"))
        self.stopBTN.setText(_translate("MainWindow", "System Stop"))
        self.startBTN.setText(_translate("MainWindow", "System Start"))
